services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 63ponira
      POSTGRES_DB: referral_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

